name: PR Workflow

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v6.1.0
